### PR TITLE
CLI 'init' command fix

### LINKED ISSUE #20: Init stack command isn't working properly
The KNoT CLI `init` command is shown in the help menu but when running it nothing happens. The weird thing about it is that if the filename and the command name are differente it works correctly. So, I'd suggest investigating if some bug was introduced when the other cloud commands were added to the CLI or if there is a bug in the `yargs` package.

### PR DESCRIPTION
**Pull request by esdrasjnr**
What does this implement/fix? Explain your changes.
---------------------------------------------------
Fix command init for knot-cloud cli:
- Fix path in copy stacks folder
- Fix path used to clone the repositories

Does this close any currently open issues?
------------------------------------------
fix #20

Any relevant logs, error output, etc?
-------------------------------------

Any other comments?
-------------------

Where has this been tested?
---------------------------
Ubuntu 18.04.3
NPM v6.13.6
NodeJS v12.13.1

### CODE REVIEW

File: src/cmds/stack/setup.js [hunk 1]
```diff
@@ -49,12 +49,14 @@ const cpDevDir = (basePath) => {
 };
 
 const initStack = (args) => {
+  const initPath = args.path || '';
```
Comment (netoax) [inline src/cmds/stack/setup.js:52]: What do you think about rename `initPath` to `path`?

**Review by netoax — CHANGES_REQUESTED** [review]

File: src/cmds/stack/setup.js (hunk 1 above)
Comment (netoax) [reply src/cmds/stack/setup.js:52]: I noticed `path` is the name of the package you're using. Sorry!

**Review by netoax — CHANGES_REQUESTED** [review]
_753b4f36da0b34af1ebc73ddf226cb938a99368b_

"Fix knot-cloud init command when there is no path **argument**. **The
repositories paths had a wrong reference.**"

_98eae4fc44428dcfed1a6a64d68e2af74c538150_

"Fix error while copying dev stack files. The copy command was **referring**
to an inexisting path."

**Comment by esdrasjnr** [comment]
> _[753b4f3](https://github.com/CESARBR/knot-cloud/commit/753b4f36da0b34af1ebc73ddf226cb938a99368b)_
> 
> "Fix knot-cloud init command when there is no path **argument**. **The repositories paths had a wrong reference.**"
> 
> _[98eae4f](https://github.com/CESARBR/knot-cloud/commit/98eae4fc44428dcfed1a6a64d68e2af74c538150)_
> 
> "Fix error while copying dev stack files. The copy command was **referring**
> to an inexisting path."

**Comment by esdrasjnr** [comment]
> _[753b4f3](https://github.com/CESARBR/knot-cloud/commit/753b4f36da0b34af1ebc73ddf226cb938a99368b)_
> 
> "Fix knot-cloud init command when there is no path **argument**. **The repositories paths had a wrong reference.**"
> 
> _[98eae4f](https://github.com/CESARBR/knot-cloud/commit/98eae4fc44428dcfed1a6a64d68e2af74c538150)_
> 
> "Fix error while copying dev stack files. The copy command was **referring**
> to an inexisting path."

@joaoaneto Done!

**Review by netoax — APPROVED** [review]
